---
title: "Alistair's temp work"
author: '500331091'
date: "2022/4/23"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
Sys.setlocale(locale = "C")
library(GEOquery)
library(tidyverse)
load("Alistair-s-temp-work.rdata")
```

```{r}
# gse1 <- getGEO("GSE129166")
# gse1 <- gse1$GSE129166_series_matrix.txt.gz
dim(gse1)
colnames(pData(gse1))
```

TCMR - T cell mediated rejection
ABMR - Antibody-mediated rejection

```{r}
# gse2 <- getGEO("GSE34748")
# gse2 <- gse2$GSE34748_series_matrix.txt.gz
dim(gse2)
colnames(pData(gse2))
```

```{r}
# gse3 <- getGEO("GSE51675")
# gse3 <- gse3$GSE51675_series_matrix.txt.gz
dim(gse3)
colnames(pData(gse3))
```
treatment: Tacrolimus vs Cyclosporine
gender & age

```{r}
# gse4 <- getGEO("GSE343")
# gse4a <- gse4$`GSE343-GPL271_series_matrix.txt.gz`
# gse4b <- gse4$`GSE343-GPL272_series_matrix.txt.gz`
dim(gse4a)
colnames(pData(gse4a))
dim(gse4b)
colnames(pData(gse4b))
```

```{r}
# gse5 <- getGEO("GSE15296")
# gse5 <- gse5$GSE15296_series_matrix.txt.gz
dim(gse5)
colnames(pData(gse5))
```
easy to clean

```{r}
# gse6 <- getGEO("GSE46474")
# gse6 <- gse6$GSE46474_series_matrix.txt.gz
dim(gse6)
colnames(pData(gse6))
```
used in the lab & assignment

```{r}
# gse7 <- getGEO("GSE50084")
# gse7 <- gse7$GSE50084_series_matrix.txt.gz
dim(gse7)
colnames(pData(gse7))
```